2020-11-24 06:12:04  ERROR - tasks_cmsGrabApi.py:82  - execute : {'errType': 'HTTPError', 'code': '-1', 'mode': 'http', 'errInfo': {'type': 'HTTPError', 'traceback': 'Traceback (most recent call last):\n  File "/headless/app/projects/MiscLib/Utils.py", line 1874, in _request_method\n    res.raise_for_status()\n  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://local-test.moagun.xyz/execute\n', 'code': '-1', 'msg': ''}} 
 - param_info : {'grab_config': {'client_name': 'commu-sender-bobae.yaml', 'grab_name': 'bobae_sender'}, 'proto': 'postmap_send', 'send_class': 'postmap', 'execute_spider': True, 'request_name': 'bobae-silo'} 

2020-11-24 06:15:22  ERROR - tasks_cmsGrabApi.py:82  - execute : {'errType': 'HTTPError', 'code': '-1', 'mode': 'http', 'errInfo': {'type': 'HTTPError', 'traceback': 'Traceback (most recent call last):\n  File "/headless/app/projects/MiscLib/Utils.py", line 1874, in _request_method\n    res.raise_for_status()\n  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://local-test.moagun.xyz/ctask/check\n', 'code': '-1', 'msg': ''}} 
 - param_info : {'grab_config': {'client_name': 'commu-sender-bobae.yaml', 'grab_name': 'bobae_sender'}, 'proto': 'postmap_send', 'send_class': 'postmap', 'execute_spider': True, 'request_name': 'bobae-silo'} 

